[package]
name = "dlp"
version.workspace = true
edition.workspace = true
description = "Shared CLI and REPL client for DLP."
license.workspace = true
repository.workspace = true
readme.workspace = true
keywords.workspace = true
categories.workspace = true

[lints]
workspace = true

[dependencies]
app-config = { path = "../app-config" }
clap.workspace = true
dlp-api = { path = "../dlp-api" }
dlp-client = { path = "../dlp-client" }
thiserror.workspace = true
tokio.workspace = true

[dev-dependencies]
control-plane = { path = "../control-plane" }
