[package]
name = "dlp-worker-pytorch"
version.workspace = true
edition.workspace = true
description = "Stub PyTorch worker implementation for DLP."
license.workspace = true
repository.workspace = true
readme.workspace = true
keywords.workspace = true
categories.workspace = true

[lints]
workspace = true

[dependencies]
clap.workspace = true
dlp-api = { path = "../dlp-api" }
dlp-client = { path = "../dlp-client" }
thiserror.workspace = true
tokio.workspace = true

[dev-dependencies]
dlp-control-plane = { path = "../dlp-control-plane" }
