[package]
name = "ui"
version.workspace = true
edition.workspace = true
description = "Leptos web UI for DLP."
license.workspace = true
repository.workspace = true
readme.workspace = true
keywords.workspace = true
categories.workspace = true

[lints]
workspace = true

[lib]
name = "ui_app"
crate-type = ["cdylib", "rlib"]

[dependencies]
console_error_panic_hook.workspace = true
dlp-client = { path = "../dlp-client" }
leptos.workspace = true

[build-dependencies]
app-config = { path = "../app-config" }
