[package]
name = "control-plane"
version.workspace = true
edition.workspace = true
description = "Axum-based control plane server for DLP."
license.workspace = true
repository.workspace = true
readme.workspace = true
keywords.workspace = true
categories.workspace = true

[lints]
workspace = true

[dependencies]
anyhow.workspace = true
app-config = { path = "../app-config" }
async-trait.workspace = true
axum.workspace = true
chrono.workspace = true
clap.workspace = true
dlp-api = { path = "../dlp-api" }
dlp-domain = { path = "../dlp-domain" }
env_logger.workspace = true
log.workspace = true
sea-orm.workspace = true
sea-orm-migration.workspace = true
serde.workspace = true
serde_json.workspace = true
tokio.workspace = true

[dev-dependencies]
serde_json.workspace = true
tower.workspace = true
